# Generated by Django 4.1.5 on 2023-11-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_snippet_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['lang', 'creation_date']},
        ),
        migrations.AddField(
            model_name='snippet',
            name='example',
            field=models.FileField(blank=True, default='None', null=True, upload_to='examples/%Y/%m/%d/', verbose_name='Пример'),
        ),
    ]
